In [1]:
import pandas as pd 
import numpy as np

In [3]:
data = pd.read_csv('../data/processed/sp500_price.csv', index_col='Date')
data.head()

,A,AAPL,ABBV,ABT,ACGL,ACN,ADBE,ADI,ADM,ADP,...,WST,WTW,WY,WYNN,XEL,XYL,YUM,ZBH,ZBRA,ZTS
Date,,,,,,,,,,,,,,,,,,,,,
2020-06-15,84.072670,83.352501,75.841026,81.956810,29.411291,185.484039,401.339996,108.362061,34.417336,133.380905,...,206.887650,176.982254,18.278782,89.813675,54.786343,60.843853,83.321045,118.745766,259.410004,127.973457
2020-06-16,84.536713,85.561523,78.269119,82.130692,29.687052,189.763962,411.670013,112.193596,35.506500,137.446915,...,207.984482,179.103897,19.047977,88.359085,54.984760,63.088249,83.703773,122.416588,266.459991,130.795959
2020-06-17,85.000763,85.442444,78.008385,83.192329,29.202093,190.506683,413.489990,112.047310,35.262535,136.450806,...,208.745407,184.449951,18.510365,86.592087,55.114147,63.248569,83.157028,119.623764,260.820007,131.323959
2020-06-18,85.281158,85.476463,78.407623,82.624901,29.049950,188.399216,420.459991,112.303322,35.358379,137.401642,...,210.128830,183.300354,18.535177,86.269928,55.648987,62.626175,82.127373,119.035332,262.230011,131.909546
2020-06-19,85.783882,84.987991,78.798721,82.990990,27.889854,187.118027,428.010010,109.898331,35.062126,134.929398,...,214.022095,176.505585,18.775038,84.727486,55.217670,61.569992,80.423401,117.895767,264.410004,131.909546

#### Daily return

In [6]:
results = data.pct_change().dropna(how='all')
results.head(5)

,A,AAPL,ABBV,ABT,ACGL,ACN,ADBE,ADI,ADM,ADP,...,WST,WTW,WY,WYNN,XEL,XYL,YUM,ZBH,ZBRA,ZTS
Date,,,,,,,,,,,,,,,,,,,,,
2020-06-16,0.005520,0.026502,0.032016,0.002122,0.009376,0.023074,0.025739,0.035359,0.031646,0.030484,...,0.005302,0.011988,0.042081,-0.016196,0.003622,0.036888,0.004593,0.030913,0.027177,0.022055
2020-06-17,0.005489,-0.001392,-0.003331,0.012926,-0.016336,0.003914,0.004421,-0.001304,-0.006871,-0.007247,...,0.003659,0.029849,-0.028224,-0.019998,0.002353,0.002541,-0.006532,-0.022814,-0.021166,0.004037
2020-06-18,0.003299,0.000398,0.005118,-0.006821,-0.005210,-0.011062,0.016857,0.002285,0.002718,0.006968,...,0.006627,-0.006233,0.001340,-0.003720,0.009704,-0.009840,-0.012382,-0.004919,0.005406,0.004459
2020-06-19,0.005895,-0.005715,0.004988,0.004431,-0.039935,-0.006800,0.017957,-0.021415,-0.008379,-0.017993,...,0.018528,-0.037069,0.012941,-0.017879,-0.007751,-0.016865,-0.020748,-0.009573,0.008313,0.000000
2020-06-22,-0.002254,0.026164,0.005790,-0.003749,0.012956,0.005210,0.024836,0.002663,-0.005964,0.009933,...,0.005587,0.025523,-0.007930,-0.039982,0.017810,0.000612,-0.004985,-0.012835,-0.009909,-0.003348

#### cumulative return

In [8]:
cumret = (1 + results).cumprod() - 1
cumret.head(5)

,A,AAPL,ABBV,ABT,ACGL,ACN,ADBE,ADI,ADM,ADP,...,WST,WTW,WY,WYNN,XEL,XYL,YUM,ZBH,ZBRA,ZTS
Date,,,,,,,,,,,,,,,,,,,,,
2020-06-16,0.005520,0.026502,0.032016,0.002122,0.009376,0.023074,0.025739,0.035359,0.031646,0.030484,...,0.005302,0.011988,0.042081,-0.016196,0.003622,0.036888,0.004593,0.030913,0.027177,0.022055
2020-06-17,0.011039,0.025074,0.028578,0.015075,-0.007113,0.027079,0.030274,0.034009,0.024557,0.023016,...,0.008980,0.042195,0.012669,-0.035870,0.005983,0.039523,-0.001968,0.007394,0.005435,0.026181
2020-06-18,0.014374,0.025482,0.033842,0.008152,-0.012286,0.015717,0.047640,0.036371,0.027342,0.030145,...,0.015666,0.035699,0.014027,-0.039457,0.015746,0.029293,-0.014326,0.002439,0.010871,0.030757
2020-06-19,0.020354,0.019621,0.038999,0.012619,-0.051730,0.008809,0.066452,0.014177,0.018734,0.011610,...,0.034485,-0.002693,0.027149,-0.056630,0.007873,0.011934,-0.034777,-0.007158,0.019275,0.030757
2020-06-22,0.018054,0.046299,0.045015,0.008822,-0.039444,0.014065,0.092939,0.016878,0.012659,0.021658,...,0.040264,0.022761,0.019004,-0.094348,0.025823,0.012554,-0.039589,-0.019901,0.009175,0.027307

#### Annualized return

In [9]:
total_days = results.shape[0]
total_days

1254

In [12]:
cumulative_return = cumret.iloc[-1]
cumulative_return

A       0.424006
AAPL    1.384811
ABBV    1.525019
ABT     0.650625
ACGL    2.039309
          ...
XYL     1.087639
YUM     0.721174
ZBH    -0.206372
ZBRA    0.128792
ZTS     0.299723
Name: 2025-06-11, Length: 491, dtype: float64

In [17]:
annualized_return = (1 + cumulative_return) ** (251 / total_days) - 1
print(f"Annualized return: \n{round(annualized_return * 100, 2)}%")

Annualized return:
A        7.33
AAPL    19.00
ABBV    20.37
ABT     10.55
ACGL    24.92
        ...
XYL     15.87
YUM     11.48
ZBH     -4.52
ZBRA     2.45
ZTS      5.39
Name: 2025-06-11, Length: 491, dtype: float64%

#### Annualized Volatility

Annualized Volatility = Daily Volatility x $\sqrt{251}$

where:
+ Daily Volatility is the standard deviation of daily return 
+ 251 is the assumed number of trading days in a year

In [21]:
daily_volatility = results.std()
annualized_volatility = daily_volatility * np.sqrt(251)

print(f'Annualized Volatility: \n{round(annualized_volatility * 100, 2)}%')

Annualized Volatility:
A       27.81
AAPL    29.89
ABBV    22.55
ABT     22.18
ACGL    26.24
        ...
XYL     26.27
YUM     20.03
ZBH     26.17
ZBRA    38.54
ZTS     25.88
Length: 491, dtype: float64%

#### Sharpe Ratio
Sharpe Ratio = (Annualized Return - Risk-Free Rate) / Annualized Volatility

where:

+ Annualized return: the annualized return of the portfolio
+ Risk-free rate: the return of a risk free asset. This is typically a small percentage, such as 0.02

In [23]:
risk_free_rate = 0.02
sharpe_ratio = (annualized_return - risk_free_rate) / annualized_volatility

print(f"Sharpe Ratio: \n{round(sharpe_ratio, 2)}")

Sharpe Ratio:
A       0.19
AAPL    0.57
ABBV    0.81
ABT     0.39
ACGL    0.87
        ...
XYL     0.53
YUM     0.47
ZBH    -0.25
ZBRA    0.01
ZTS     0.13
Length: 491, dtype: float64

#### Max Drawdown